---
title: "Gaussian Processes in Stan"
output: html_notebook
runtime: shiny
---

This notebook is a tutorial on Gaussian Processes using Stan that accompanies the youtube video. 
```{r}
require(rstan)
```
# Simulating from a gaussian process
```{r}
N=100

data = list(
  N = N,
  x = seq(-10, 10, length.out=N), #equally spaced points
  alpha = 1,
  rho = 1
)
```

```{r}
ndraws = 50 # number of draws
fit = stan(file='sim_gp.stan', data=data, algorithm ='Fixed_param',warmup = 0, chains = 1, iter=ndraws)
```
```{r}
params = extract(fit)
```

```{r}
xr=c(-10,10)
yr=c(-5,5)
plot(xr, yr, ty='n')
for(i in 1:ndraws){
  lines(data$x, params$f[i,], pch=20, col=rgb(0,0.55,0.5, 0.2), cex=0.5)
}
points(data$x, params$f[ndraws,], pch=20, col='black', cex=1)
lines(data$x, colMeans(params$f),lwd=3)

```
```{r}
yconf = sapply(1:N, function(x) quantile(params$f[,x], probs=c(0.003,0.05,0.32,0.68,0.95,0.997)))

plot(xr,yr, ty='n', xlab='t', ylab='y')
for(i in 1:3){
  polygon(x=c(data$x, rev(data$x)), y=c(yconf[i,], rev(yconf[i+3,])), border=NA, col=rgb(0,0,0,0.1))
}
lines(data$x, colMeans(params$f),lwd=3)
```
# Kepler data
Read in Kepler data for object KEPLAR 003632418
```{r}
lcdata = read.csv('kplr003632418-2009131105131_llc.csv')
```

```{r}
plot(lcdata$TIME, lcdata$SAP_FLUX, pch=20, xlab='Time [days]', ylab='Flux [e-/s]', cex=0.5)
```
```{r}
bad = which(is.na(lcdata$SAP_FLUX)) #remove missing data
x = lcdata$TIME[-bad] 
y = (lcdata$SAP_FLUX[-bad] - mean(lcdata$SAP_FLUX[-bad]))/sd(lcdata$SAP_FLUX[-bad]) #Normalise flux to have mean 0 and sd 1
```

```{r}
plot(x,y, pch=20, cex=0.5)
```

```{r}
data = list(
  N = length(x),
  x = x,
  y = y
)
```


```{r}
fit = stan(file='method2.stan', data=data,chains = 1, iter=2000)
```

```{r}
params = extract(fit)
```

```{r}
pairs(fit)
```
```{r}
mean(params$rho)
mean(params$alpha)
mean(params$sigma)
```

```{r}
N =500
gen_data = list(
  N = N,
  x = seq(120, 132, length.out=N), #equally spaced points
  alpha = mean(params$alpha),
  rho = mean(params$rho), 
  sigma = mean(params$sigma)
)

ndraws = 50 # number of draws
gen_sam = stan(file = 'sim_gp.stan', data=gen_data, algorithm ='Fixed_param', warmup = 0, chains = 1, iter=ndraws)
```

```{r}
gen_params = extract(gen_sam)
xr = c(120,132)
yr = c(-4,4)
plot(xr, yr, ty='n')
for(i in 1:ndraws){
  lines(gen_data$x, gen_params$f[i,], pch=20, col=rgb(0,0.55,0.5, 0.2))
}
points(x, y, pch=20, col='orange', cex=0.5)
legend('topright', y = c('predicted','data'), col = c(rgb(0,0.55,0.5, 0.2),'orange'), bty='n', pch=c(NA,20), lty=c(1,NA))
```
# Predictive inference 

```{r}
N_predict = 100
x_predict = seq(range(data$x)[1], 132, length.out=N_predict)
N_obs = 200
Obs = sort(sample(1:length(x), N_obs))
pred_data <- list(N1=N_obs, x1=x[Obs], y1=y[Obs], N2=N_predict, x2=x_predict)

pred_fit = stan(file='method1.stan', data =pred_data, iter=2000, chains=1)
```
```{r}
pred_params = extract(pred_fit)
```

```{r}
yr = c(-2,2)
xr = c(120, 132)
plot(xr, yr, ty='n')
for( i in 1:100){
  lines(x_predict, pred_params$f[i,(N_obs+1):(N_obs+N_predict)], col=rgb(0,0,0,0.1))
}
points(data$x, data$y, pch=20, col='orange', cex=0.3)
```
```{r}
N_predict = 100
x_predict = seq(range(x)[1], 132, length.out=N_predict)
N_obs = 3
Obs = sort(sample(1:length(x), N_obs))
pred_data <- list(rho=mean(params$rho),alpha=mean(params$alpha), sigma=mean(params$sigma), N=N_obs, x=x[Obs], y=y[Obs], N_predict=N_predict, x_predict=x_predict)

pred_opt_fit <- stan(file='predict_gauss.stan', data=pred_data, iter=1000, warmup=0,
                     chains=1, algorithm="Fixed_param")
```

```{r}
pred_params = extract(pred_opt_fit)
```

```{r}
yr = c(-2,2)
xr = c(120, 132)
plot(xr, yr, ty='n')
for( i in 1:100){
  lines(x_predict, pred_params$f_predict[i,], col=rgb(0,0,0,0.1))
}
points(x, y, pch=20, col='orange', cex=0.3)
points(pred_data$x, pred_data$y, pch=20, col='orange', cex=2)
points(pred_data$x, pred_data$y, cex=2)
```
```{r}
yconf = sapply(1:N_predict, function(x) quantile(pred_params$f[,x], probs=c(0.003,0.05,0.32,0.68,0.95,0.997)))

plot(xr,yr, ty='n', xlab='t', ylab='y')
for(i in 1:3){
  polygon(x=c(x_predict, rev(x_predict)), y=c(yconf[i,], rev(yconf[i+3,])), border=NA, col=rgb(0,0,0,0.1))
}
lines(x_predict, colMeans(pred_params$f),lwd=3)

```


