---
title: "Visualisations of Gaussian Process Kernels"
output: html_notebook
runtime: shiny
---

```{r}
require(shiny)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Covariance kernels
### RBF kernel
$$
\alpha ^2 \exp\left(-\frac{(x - x')^2}{2\rho^2}\right)
$$

```{r RBFkernel, echo=FALSE, fig.width=4, fig.height=4}
inputPanel(
  sliderInput("alpha", label = "alpha:",
              min = 0, max = 1, value = 1, step = 0.1),

  sliderInput("rho", label = "rho:",
              min = 0.1, max = 2, value = 1, step = 0.2)
)

renderPlot({
  par(oma=c(0,0,0,0),mar=c(0,0,0,0))
  N=10
  x=seq(-5,5,length.out=N)
  cov = matrix(nrow = N, ncol=N)
  for(i in 1:N){
    for(j in 1:N){
      cov[i,j] = input$alpha^2 * exp(-0.5 * (x[i]-x[j])^2 / (input$rho^2))
    }
  }
  image(cov, ylim=c(1.1,-0.1), axes=FALSE, col=gray.colors(50, start=0, end=input$alpha))

})
```

### Periodic Kernel
$$
\alpha^2 \exp\left(-\frac{2 \sin^2(\pi|x-x'|/p)}{\rho^2}\right)
$$

```{r periodickernel, echo=FALSE, fig.width=3, fig.height=3}
inputPanel(
  sliderInput("alphapk", label = "alpha:",
              min = 0, max = 1, value = 1, step = 0.1),

  sliderInput("rhopk", label = "rho:",
              min = 0.1, max = 2, value = 1, step = 0.2),

  sliderInput("p", label = "p:", #periodicity
              min = 0, max = 3.14, value = 1, step = 0.1)
)

renderPlot({
  par(oma=c(0,0,0,0),mar=c(0,0,0,0))
  N=10
  x=seq(-5,5,length.out=N)
  cov = matrix(nrow = N, ncol=N)
  for(i in 1:N){
    for(j in 1:N){
      cov[i,j] = input$alphapk^2 * exp(-2.0 * sin(pi* abs(x[i]-x[j]) / input$p)^2 / (input$rhopk^2))
    }
  }

  image(cov, ylim=c(1.1,-0.1), axes=FALSE, col=gray.colors(50, start=0, end=input$alphapk))

})
```